# Site settings
title: StarkDroid
email: gamerprince.exp@gmail.com
description: The Jekyll version of the Identity theme by HTML5 UP.
baseurl: "/identity-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Identity
your-name: M.Trishiraj
your-title: Lead Developer of ZephyrOS
your-tagline: Student, foodie, VELSguy 

# Social settings
500px_url:
facebook_url: https://facebook.com/trishi.raj
github_url: https://github.com/StarkDroid
gitlab_url: 
googleplus_url: https://plus.google.com/u/0/+starkdroidTTD
instagram_url: https://instagram.com/solitary_reaper007
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
